/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dialogs: typeof import('./src/components/dialogs/Dialogs.vue')['default']
    ElButtom: typeof import('element-plus/es')['ElButtom']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElContanier: typeof import('element-plus/es')['ElContanier']
    ElContianer: typeof import('element-plus/es')['ElContianer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    Fb: typeof import('./src/components/fb.vue')['default']
    Foot: typeof import('./src/components/foot.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hb: typeof import('./src/components/hb.vue')['default']
    Head: typeof import('./src/components/head.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Header1: typeof import('./src/components/Header1.vue')['default']
    HeaderBook: typeof import('./src/components/header-book.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
